### ISSUE TITLE
提交结果中失败用例为缺陷,所属产品等基本信息问题（待回复）

### ISSUE THREAD

**Issue by TiashaChristabel** [easysoft/zentaoatf#10]
禅道版本：企业版5.0.1
help_show怎么用。这个提交页面，我是用鼠标点的；第一行“登出n: default=Trunk” 是什么意思 ？
![image](https://user-images.githubusercontent.com/88478996/128309632-33567463-e009-4266-88a7-8612402e914b.png)
提交结果中失败用例为缺陷,bug的基本信息也有问题。。。。
![image](https://user-images.githubusercontent.com/88478996/128309679-e8ddb0ca-4900-476a-bc4b-35a8fc7c57e1.png)

**Comment by aaronchen2k** [comment]
测试了一下最新的ZTF2.4和禅道开源版15.6，是成功的。
第一行显示的问题，在终端窗口高度不够的情况下，GUI会有重叠，请确认是否是这个引起的；
提交的产品和模块取值不对的问题，请加上--verbose参数执行，将日志发给禅道技术支持，或贴在这里我来转发过去。

![image](https://user-images.githubusercontent.com/3222874/143513546-245fd811-0476-43f1-a149-a2d8b8cb15a5.png)
