### ISSUE TITLE
go build无法找到res模块

### ISSUE THREAD

**Issue by TianShan95** [easysoft/zentaoatf#13]
你好，非常感谢你们开发的自动测试框架。
在我重新编译 ztf.go 时，模块res发生报错，提示找不到。
在 i118.go文件引入了res，但是我在res文件夹并未找到res包的定义？
谢谢。
<img width="904" alt="截屏2022-01-10 下午6 31 03" src="https://user-images.githubusercontent.com/67675520/148752170-8b67083f-21fb-4c02-a8b9-89bc8cf31f84.png">

**Comment by aaronchen2k** [comment]
执行一下Makefile文件里的go-bindata开头的命令，生成res.go即可。

**Comment by aaron951117** [comment]
感谢您的及时回复，已解决。
