### ISSUE TITLE
ZTF2.5版本，提交测试结果至禅道失败

### ISSUE THREAD

**Issue by lenghanyou** [easysoft/zentaoatf#14]
![image](https://user-images.githubusercontent.com/102897016/161418556-b8d792c6-fc6f-4933-afb3-e6d510e52089.png)
1：输入测试任务id，输的是937
2：输入为空，结果也是一样，提交测试结果至禅道失败

**Comment by aaronchen2k** [comment]
用户权限的问题，请联系管理员，后台给用户增加ci模块的commitresult方法权限。

**Comment by lenghanyou** [comment]
感谢，已解决
