### ISSUE TITLE
ZTF2.5失败用例提交BUG，报优先级应当是数字

### ISSUE THREAD

**Issue by lenghanyou** [easysoft/zentaoatf#15]
![image](https://user-images.githubusercontent.com/102897016/161418799-c887d9de-fa16-4b3c-b8ce-c0120cca6b2f.png)
![image](https://user-images.githubusercontent.com/102897016/161418834-528a31b7-c507-4e63-8731-61882e2421de.png)

**Comment by aaronchen2k** [comment]
请参照这里是指下字符集，用命令ztf.exe cb log/005 --verbose试一下，截屏输出消息。
pri优先级的值应该为数字。
<img width="255" alt="image" src="https://user-images.githubusercontent.com/3222874/162094425-d69ecb66-a229-4c6e-ab19-c6803b8a2ba5.png">
