### ISSUE TITLE
cr 报错 post request return '400 Bad Request'

### ISSUE THREAD

**Issue by yuaiwuhen** [easysoft/zentaoatf#22]
### 环境描述
【ztf 版本】：截止于2022年4月21日的版本（ztf versin 没有具体版本信息），windows版；
【系统环境】：windows 11， cmd；
【禅道版本】[ZenTaoPMS16.5开源版]
(https://www.zentao.net/dl/zentao/16.5/ZenTaoPMS.16.5.old.exe)
### 输入
![image](https://user-images.githubusercontent.com/19143587/164614950-ac5bdfac-6c10-4c92-b79b-2010ad2ecd7f.png)

let a=1
命令：  .\ztf.exe cr .\log\001\

错误信息：
post request return '400 Bad Request'.
提交测试结果到禅道失败，错误400 Bad Request。

**Comment by aaronchen2k** [comment]
Fixed, add product param if running from cmd line.
