### ISSUE TITLE
xtf推送到禅道成功，动态能看到，但是在测试单下面没有相应记录

### ISSUE THREAD

**Issue by wendy1901** [easysoft/zentaoatf#23]
![07b17856f1f7b5087fbab7a1e569f0d](https://user-images.githubusercontent.com/31026667/173263619-e09f26b4-6949-40ec-80b3-d8b77869e4e9.png)
禅道上个人动态出现一条记录 但没有专门的列表入口可以查看。动态入口的链接是testtask-view-13.html
![10568d9fd7c76c1af99c1b7d250ae0f](https://user-images.githubusercontent.com/31026667/173263672-32c87577-45fa-492e-8b48-9b5a816d60dc.png)
本应该出现在测试单列表页，却没有这条记录

**Comment by wendy1901** [comment]
![95a2ab9091ecf443b94e0404a6907009_](https://user-images.githubusercontent.com/31026667/173263833-39799efc-f165-4afa-bbfc-5adb9fcf69c3.png)

**Comment by aaronchen2k** [comment]
单元测试结果在测试->用例->单元测试下；功能测试的在测试->测试单模块下。
