### ISSUE TITLE
执行 ztf.exe co 检出的用例，无法检出步骤

### ISSUE THREAD

**Issue by clobob** [easysoft/zentaoatf#3]
执行 ztf.exe co
选套件
选python
其他选默认

获取到的用例**缺少**用例步骤

禅道上的用例图示：
![用例步骤](https://user-images.githubusercontent.com/10508051/78504600-df1e5080-77a0-11ea-91c9-6da8538d9249.jpg)

实际获取到的用例是这样的
![检出的用例-缺失了步骤](https://user-images.githubusercontent.com/10508051/78504633-037a2d00-77a1-11ea-97a9-14cbfcf9d727.jpg)

**Comment by clobob** [comment]
另问一个问题：
实际的测试脚本是保存到一个版本库进行维护吗？

**Comment by easysoft** [comment]
步骤的问题我让陈哥看看。测试脚本和正常的代码一样，应当放到版本库里面进行维护。

**Comment by clobob** [comment]
> 步骤的问题我让陈哥看看。测试脚本和正常的代码一样，应当放到版本库里面进行维护。

那我就有第二个问题了：
本地脚本我感觉没有上传到禅道，因为执行更新后，步骤被更新在禅道可见，但是脚本在禅道不可见

**Comment by aaronchen2k** [comment]
考虑到脚本和用例一般不是一对一的关系，脚本本身也有很多的类库和工具的依赖，所以没有在禅道中管理脚本。

**Comment by clobob** [comment]
> * 第一个问题确认了一下，目前导出时，没有把用例步骤导出来；导入时会更新用例步骤到禅道；
> * 第二个问题，考虑到脚本和用例一般不是一对一的关系，脚本本身也有很多的类库和工具的依赖，自动化测试项目更适合用版本系统来管理，所以没有在禅道中管理脚本。

这样的实现与实际的工作流程不容易配合，例如如下场景：
前提条件： 已经建立好100条自动化用例保存到git仓库，也更新了禅道的用例库。
新建了一个测试单，关联了其中的50条用例，分配给自动化组。
这时就用ztf现有的命令和流程来运行和汇总这50条的结果，就会很困难
因为如果直接 ztf co 这个测试单，只能获取到用例的 产品id，用例id，用例title
而如果用git checkout用例的话，就会获取所有100条用例
请问，这种应用场景ztf如何来应对？

**Comment by aaronchen2k** [comment]
您的建议是？

**Comment by clobob** [comment]
目前没有好的想法，请关闭这个问题吧，谢谢
