### ISSUE TITLE
执行 ztf.exe cr 提交测试结果，测试单中的测试用例状态没有更新，仍是未执行状态

### ISSUE THREAD

**Issue by jjxxff2000** [easysoft/zentaoatf#4]
测试单是分配给测试人员执行用例的，执行ztf.exe cr 后测试单下的用例测试结果并未更新，但是用例结果集的状态进行了更新。
测试单的用例未更新
<img width="850" alt="禅道1" src="https://user-images.githubusercontent.com/20653208/78790206-c7350f80-79e0-11ea-81ed-2f465881072a.png">

用例下的用例已更新
<img width="842" alt="禅道2" src="https://user-images.githubusercontent.com/20653208/78790269-db790c80-79e0-11ea-8ffb-2f4e87a728b3.png">

**Comment by aaronchen2k** [comment]
目前导出的用例脚本是未记录taskId的信息的（包括从task导出的用例），故执行结果对应不到某个测试单。我们会考虑您的建议，做相应的关联，谢谢。

**Comment by jjxxff2000** [comment]
嗯，我们公司一直在使用禅道产品，尤其是atf问世后，感觉更是弥补了测试自动化方面的需求，还请考虑下测试单下的用例执行。
公司这边一直以任务关联测试单最后再和具体的测试用例挂钩。

**Comment by easysoft** [comment]
我们2.2发布了，可以支持单元测试的结果了。测试单的这个支持我们下个版本做。敬请关注。

**Comment by aaronchen2k** [comment]
已支持，关闭

![image](https://user-images.githubusercontent.com/3222874/80177425-57549500-862e-11ea-8b3d-b372f44f8cde.png)
