### ISSUE TITLE
demo\lang\php\1_string_match.php 执行异常

### ISSUE THREAD

**Issue by yangjinlian99** [easysoft/zentaoatf#5]
脚本中：
[group]
  2. regular expression match >> 1\d{10}
  3. format string match >> %s%d
执行不通过。

执行结果：
(1/1) Fail [D:\ztf\demo\lang\php\1_string_match.php] [0. check string matches pattern] (0.00s)

Failed Scripts:
[D:\ztf\demo\lang\php\1_string_match.php] 0.check string matches pattern
Step 2: Fail
[Expect] 1\d{10}
[Actual] 13905120512

Step 3: Fail
[Expect] %s%d
[Actual] abc123

2020-07-30 08:50:23 Run 1 scripts in 0 sec, 0(0.0%) Pass, 1(100.0%) Fail, 0(0.0%) Skip. Report D:\ztf\log\004\result.txt

**Comment by aaronchen2k** [comment]
为避免期待结果的解析有歧义，新版修改为：使用反引号`将正则表达式括起来。
