### ISSUE TITLE
提交bug命令界面展示错误

### ISSUE THREAD

**Issue by shirlyzhou2017** [easysoft/zentaoatf#7]
os：win10 64位
ztf设置：中文，
当前代码页：65001或437
字体：16，仿宋
【步骤】
1、执行ztf.exe cb log\001
2、选择要提交缺陷的用例
【结果】
进入缺陷提交页面，页面展示错位

**Comment by aaronchen2k** [comment]
请执行以下命令查看下编码，确认是否是437：
C:\ztf>chcp
Active code page: 437
