### ISSUE TITLE
ztf提交结果到禅道后，测试用例状态和测试结果未更新（已转发）

### ISSUE THREAD

**Issue by wangJUN1992** [easysoft/zentaoatf#9]
禅道版本：pro 9.0.3

使用ztf从禅道导出测试用例后，执行测试脚本后，提交结果到禅道，记录提交成功，但是测试用例状态和测试结果未更新

![1625038085(1)](https://user-images.githubusercontent.com/37613261/123919734-d0c8df80-d9b7-11eb-80e2-ae9a15975e13.jpg)

![))R%@@X_5I2$OHWY3CVN6_X](https://user-images.githubusercontent.com/37613261/123919524-98290600-d9b7-11eb-9685-505059e4a9ec.png)
![))HN~_3D@(I8@1TD{E}1@@O](https://user-images.githubusercontent.com/37613261/123919564-a119d780-d9b7-11eb-9494-533f4fbb19ef.png)

**Comment by aaronchen2k** [comment]
已转服务端开发

**Comment by aaronchen2k** [comment]
Reopen

![image](https://user-images.githubusercontent.com/3222874/143512795-27f397ad-6b1a-4797-91f1-86b2b9400bb8.png)

请求地址：
http://localhost:20080/user-login.json?zentaosid=h3jvmvprrc8hjoqhthcboqlrbd&XDEBUG_SESSION_START=PHPSTORM
请求参数：
account=admin&password=P2ssw0rd
服务返回：
map[status:success user:map[account:admin address: admin:true analysis: avatar: birthday:0000-00-00 clientLang:zh-cn clientStatus:offline commiter: company:deeptest dept:0 dingding: email: fails:0 gender:f groups:[] id:1 ip:172.17.0.1 join:0000-00-00 last:2021-11-26 09:16:23 lastTime:1637889246 locked:0000-00-00 00:00:00 mobile: modifyPassword:false nature: nickname: phone: pinyin: qq: ranzhi: realname:admin rights:map[acls:[] projects: rights:[]] role: score:0 scoreLevel:0 skype: slack: strategy: token:h3jvmvprrc8hjoqhthcboqlrbd type:inside view:map[account:admin products:1,2 programs:6 projects:7 sprints:1,2,7,6] visits:19 weixin: whatsapp: zipcode:]]
登录成功。

请输入 测试任务Id，默认为空则新建。


请求地址：
http://localhost:20080/user-login.json
请求参数：
password=P2ssw0rd&account=admin
服务返回：
map[status:success user:map[account:admin address: admin:true analysis: avatar: birthday:0000-00-00 clientLang:zh-cn clientStatus:offline commiter: company:deeptest dept:0 dingding: email: fails:0 gender:f groups:[] id:1 ip:172.17.0.1 join:0000-00-00 last:2021-11-26 09:16:23 lastTime:1637889246 locked:0000-00-00 00:00:00 mobile: modifyPassword:false nature: nickname: phone: pinyin: qq: ranzhi: realname:admin rights:map[acls:[] projects: rights:[]] role: score:0 scoreLevel:0 skype: slack: strategy: token:h3jvmvprrc8hjoqhthcboqlrbd type:inside view:map[account:admin products:1,2 programs:6 projects:7 sprints:1,2,7,6] visits:19 weixin: whatsapp: zipcode:]]
登录成功。

请求地址：
http://localhost:20080/ci-commitResult-.json?zentaosid=h3jvmvprrc8hjoqhthcboqlrbd&XDEBUG_SESSION_START=PHPSTORM
请求参数：
{"env":"mac","testType":"func","testFrame":"ztf","productId":1,"taskId":0,"zentaoData":"","buildUrl":"","pass":3,"fail":1,"skip":0,"total":4,"startTime":1637888894,"endTime":1637888894,"duration":0,"funcResult":[{"id":1,"productId":1,"path":"/Users/aaron/rd/project/zentao/go/ztf/product1/1.php","status":"pass","title":"售后服务的","steps":[{"id":"1.","name":"","status":true,"checkPoints":[{"numb":1,"expect":"正常显示","actual":"正常显示","status":true}]}]},{"id":2,"productId":1,"path":"/Userrd/project/zentao/go/ztf/product1/2.php","status":"fail","title":"首页的测试用例","steps":[{"id":"1.","name":"","status":false,"checkPoints":[{"numb":1,"expect":"正常ual":"错误显示","status":false}]}]},{"id":3,"productId":1,"path":"/Users/aaron/rd/project/zentao/go/ztf/product1/3.php","status":"pass","title":"新闻中心的测试用例",":"1.","name":"","status":true,"checkPoints":[{"numb":1,"expect":"正常显示","actual":"正常显示","status":true}]}]},{"id":4,"productId":1,"path":"/Users/aaron/rd/projao/go/ztf/product1/4.php","status":"pass","title":"成果展示测试用例","steps":[{"id":"1.","name":"","status":true,"checkPoints":[{"numb":1,"expect":"正常显示","actualatus":true}]}]}],"unitResult":null}
服务返回：
map[result:success]

提交测试结果到禅道成功。
================================================================================= = ================================================================================

Exiting.
